### PR TITLE
Linux docker support

### PR DESCRIPTION
**Pull request by 0Xellos**

### CODE REVIEW

**Comment by DJSchaffner** [comment]
Couldn't really test it on Linux right now, but the windows part of it seems to still work, so I'll merge it.
Thanks for your contribution!

**Comment by Arkanosis** [comment]
Oh, wow, this is so cool!

I've been thinking for months about running this very promising tool on Linux, thanks!

Is the ` docker/requirements-freeze.txt` file really supposed to be commited, though? At the very least, the current content doesn't looks very useful.

Thanks again!

**Comment by DJSchaffner** [comment]
Thanks for the feedback on this. You are probably right, I will remove it from the repository

**Comment by 0Xellos** [comment]
@Arkanosis At the moment it's mostly so you know if a version of some dependency changed, I use it in other projects. Installing from it instead of requirements.txt would probably be a better option but I never got to it. In this case I don't really care.

**Pull request merged**
